### ISSUE TITLE
AirQuality parameter - HK compliance

### ISSUE THREAD

**Issue by To-Azamat** [smallwood69/homebridge-cgllc-airmonitor-s1#2]
Good day!

According to Apple Developers Kit AirQuality parameter must consist of 6 positions, including Unknown. As the plugin has only 5 positions, creating automation in HK translates into nonsense in Eve.

Here’s the answer from Eve’s developer:
—-
Please make sure homebridge plugins follow the HomeKit specification. The Eve app only supports accessories that are in line with the specification. Air Quality requires those 6 values, but their names are not strictly defined.
The choice of options for a trigger is a user interface design decision and at its core doesn’t influence how rules work. The additional option of being able to trigger on a certain state is helpful for some users, but can be safely ignored if not needed.
—-

Also no matter how I tried I wasn’t able to trigger automations based on AirQuality. Can it be the reason?

**Comment by smallwood69** [comment]
I don't think so, but
I'll check it out.

**Comment by smallwood69** [comment]
Dear To-Azamat .

I fixed the issue.

Thank you.

**Comment by To-Azamat** [comment]
Thank you, did some testing (not all possible combinations, but several) and can confirm automations based on AirQuality now trigger properly.

But automations created in HomeKit still have their triggers ported incorrectly into Eve.

**Comment by smallwood69** [comment]
I didn't understand exactly.
Are you saying that the plugin doesn't provide the correct information?

**Comment by To-Azamat** [comment]
I am not sure what exactly happens, could be plugin or HK/Eve. 

What exactly I see: when I create auto in HK with trigger "On AQ above BAD" in Eve in the same auto I see trigger "On AQ above GREAT". Just replicated it. Other triggers do not port correctly as well, though I did not try all combos.
The autos created in Eve port correctly to HK, so it is one-way problem.

**Comment by smallwood69** [comment]
I think it's because of the difference between EVE and C/G measurement criteria.

**Comment by smallwood69** [comment]
Perhaps it is created incorrectly in HK.
It is displayed differently from HK in Home+  and Controller.

**Comment by To-Azamat** [comment]
Can't say. The only thing I can think about is different number of trigger states. Eve uses 6, plugin uses 5. This way state "1" will be different for 2 apps. Though can't understand why it works from Eve to HK.

Btw I observe the same behaviour for Air Purifier 3H - wrong autos porting to Eve. So probably you are correct that there are some incompatibility with Eve, though they are claiming to be 100% HK compliant.

**Comment by smallwood69** [comment]
HOME+ and Controller display the same as HK.
I think it's an EVE error.

**Comment by To-Azamat** [comment]
Can be, they have a lot of bugs )
I will contact them with our findings. 

One more question reg plugin: is it possible to add temp/humidity readings as triggers in HK? I can use AQ only.

**Comment by smallwood69** [comment]
If you use Home+ or Controller for HomeKit , you can use templature  And humidity 

Controller for HomeKit  is free, Home+ is not. 
https://apps.apple.com/us/app/controller-for-homekit/id1198176727
